**欧式距离：(Euclidean distance)**

$$d(X,Y) = \sqrt{\sum_{i=1}^n(x_i-y_i)^2}$$
<ul>
    <li>对称性</li>
    <li>非负性</li>
    <li>三角不等式</li>
</ul>

**闵可夫斯基距离：（Minkowski distance）**
$$d(X,Y) = \left( \sum_{i=1}^n|x_i-y_i|^r \right)^{1/r} $$
*作为闵可夫斯基距离的推广得到 欧几里得距离*


In [66]:
'''
k-邻近算法
'''
import numpy as np
import matplotlib as plt
import operator

def createDataSet():
    group = np.array([[1,1.1],[1,1],[0,0],[0,1.1]])
    labels = ['A','A','B','B']
    return group,labels
group,labels = createDataSet()
test = np.tile([1,2],(2,2))
display(test)
#test.sum(axis=1)
#test.argsort()
xx = {"a":4,"c":1,"b":2}
#sorted(xx.iteritems(),key=operator.itemgetter(1),reverse=True)
display(sorted(xx.iteritems(),key=operator.itemgetter(1),reverse=False))


array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

[('c', 1), ('b', 2), ('a', 4)]

In [72]:
def classify(inX,dataSet,labels,k):
    dataSetSize =dataSet.shape[0] # 数据的维度
    diffMat = np.tile(inX,(dataSetSize,1))-dataSet  #向量差   # np.tile 复制一个矩阵  
    #display(diffMat)
    sqDiffMat = diffMat**2
    sqDisances = sqDiffMat.sum(axis=1) # 向量距离 
    distances = np.sqrt(sqDisances)
    #display(distances)
    sortedDistIndicies = distances.argsort() #返回排序后的索引默认真正序
    #display(sortedDistIndicies)
    classCount = {}
    for i in range(k):
        votelabel = labels[sortedDistIndicies[i]]
        classCount[votelabel] = classCount.get(votelabel,0)+1 #get(key,default)
    sortedClassCount = sorted(classCount.iteritems(),key=operator.itemgetter(1),reverse=True)  
    '''
    sorted iteritems()以元组的方式迭代每队值  reverse 排序 True 倒序  False  正序
    ''' 
    #display(sortedClassCount)
    return sortedClassCount[0][0]

classify([0,0],group,labels,3)
    
    

array([[-1. , -1.1],
       [-1. , -1. ],
       [ 0. ,  0. ],
       [ 0. , -1.1]])

array([ 1.48660687,  1.41421356,  0.        ,  1.1       ])

array([2, 3, 1, 0], dtype=int64)

[('B', 2), ('A', 1)]

'B'